sonar.projectKey=105Proyect
sonar.projectName=105Proyect
sonar.sources=app,resources
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**
sonar.host.url=http://localhost:9000
sonar.token=sqp_8e1d727ae296e891aa878d73a4f66111039192d9